languageCode = "en"
languageName = "English"
weight = 1

title = "jonasg.io "

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false
  dateFormat = "2 January 2006"


[params.author]
   name = "Jonas Geiregat"
   image = "img/author.png"
   headline = "System Designing Software Developer"
   links = [
     { github = "https://github.com/jonas-grgt" },
     { linkedin = "https://www.linkedin.com/in/jonasgeiregat" },
     { twitter = "https://twitter.com/jonas_grgt" },
   ]
